### ISSUE TITLE
use GPIO to simulate iic interface,failed to initialize soundcards 

### ISSUE THREAD

**Issue by xuganlai** [OpenNuvoton/NUC970_Linux_Kernel#13]
the system startup print below:
-----------------------------------------------------------------------------------------------
nuc970-audio nuc970-audio: ASoC: CODEC nau8822.0-001a not registered
nuc970-audio nuc970-audio: snd_soc_register_card() failed: -517
platform nuc970-audio: Driver nuc970-audio requests probe deferral
TCP: cubic registered
NET: Registered protocol family 17
NET: Registered protocol family 15
i2c-gpio i2c-gpio.2: using pins 193 (SDA) and 192 (SCL)----------why 193,192???
nuc970-audio nuc970-audio: ASoC: CODEC nau8822.0-001a not registered
nuc970-audio nuc970-audio: snd_soc_register_card() failed: -517
platform nuc970-audio: Driver nuc970-audio requests probe deferral
UBI: attaching mtd2 to ubi0
UBI: scanning is finished
UBI: volume 0 ("rootfs") re-sized from 190 to 232 LEBs
UBI: attached mtd2 (name "rootfs", size 32 MiB) to ubi0
UBI: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
UBI: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
UBI: VID header offset: 2048 (aligned 2048), data offset: 4096
UBI: good PEBs: 256, bad PEBs: 0, corrupted PEBs: 0
UBI: user volume: 1, internal volumes: 1, max. volumes count: 128
UBI: max/mean erase counter: 1/0, WL threshold: 4096, image sequence number: 1867020530
UBI: available PEBs: 0, total reserved PEBs: 256, PEBs reserved for bad PEB handling: 20
UBI: background thread "ubi_bgt0d" started, PID 462
nuc970-rtc nuc970-rtc: setting system clock to 2005-01-10 19:18:38 UTC (1105384718)
ALSA device list:
  No soundcards found.

-------------------------------------------------------------------------------------------------------
below is my config:
1、
.config - Linux/arm 3.10.107 Kernel Configuration
 > Device Drivers > I2C support > I2C Hardware Bus support 

*** I2C system bus drivers (mostly embedded / system-on-chip) *** 
< > CBUS I2C driver      
< > Synopsys DesignWare Platform
<*> GPIO-based bitbanging I2C
< > NUC970 I2C Driver for Port 0
< > NUC970 I2C Driver for Port 1  
< > OpenCores I2C Controller

2、modify i2c_gpio_adapter_data structure(arch/arm/mach-nuc970/dev.c),
.sda_pin=NUC970_PG1	//use PG0 as SDA
.scl_pin=NUC970_PG0	//use PG1 as SCL

which settings are ignored?
thanks.

**Comment by yachen** [comment]
The setting looks fine. Are you using NUC972 DEV board? Have you turned SW15 to ON?

Each port reserved 32 GPIOs although 16 will be used at most. So PA0 = 0, PA1 = 1,.. PB0 = 32...PG0=192, GP1=193...


Sincerely,

Yi-An Chen

**Comment by xuganlai** [comment]
the SW15 of nuc972 demo board  is ON.
<*> NUC970 I2C Driver for Port 0---->the option is selected,there is no problem.that's to say hardware is ok.

**Comment by xuganlai** [comment]
I can't find any problems.could you try it on DEV board for me?
thanks.

**Comment by yachen** [comment]
I can reproduce this issue on DEV board. But I'm working on other project, will solve this issue later.


Sincerely,

Yi-An Chen

**Comment by yachen** [comment]
Hi,

1. Add 8822 ID in nuc970_i2c_clients2[] in arch/arm/mach-nuc970/dev.c
2. Replace nau8822.0-001a with nac8822.2-001a in sound/soc/nuc970


Sincerely,

Yi-An Chen

**Comment by xuganlai** [comment]
thank you very much.the problem has been Solved.will make a test for a long time.
