### ISSUE TITLE
There are may be memory leak in Linux Kernel?

### ISSUE THREAD

**Issue by 248668342** [OpenNuvoton/NUC970_Linux_Kernel#16]
NUC972 hardware platform;
kernel version:3.10.x
issue date: 2016.11.08
Long time running test,there are may be some driver caused memory leak.
The free command presents the memory used and free,but used memory increase every ten days.

**Comment by yachen** [comment]
Hi,

Please sync latest code and test again. Also you need to provide more information if need us to check this issue.


Sincerely,

Yi-An Chen

**Comment by junwushi** [comment]
sorry,my application isues
