### ISSUE TITLE
after update 2c90956      Add power-on-setting check to nand driver  then can't mount the rootfs

### ISSUE THREAD

**Issue by junwushi** [OpenNuvoton/NUC970_Linux_Kernel#19]
1.780000] DCCP: Activated CCID 2 (TCP-like)
[    1.790000] DCCP: Activated CCID 3 (TCP-Friendly Rate Control)
[    1.800000] sctp: Hash tables configured (established 2048 bind 4096)
[    1.810000] NET: Registered protocol family 21
[    1.820000] Registered RDS/tcp transport
[    1.820000] NET: Registered protocol family 36
[    1.830000] Key type dns_resolver registered
[    1.840000] Key type encrypted registered
[    1.850000] nuc970-rtc nuc970-rtc: setting system clock to 2017-02-14 09:34:07 UTC (1487064847)
[    1.860000] yaffs: dev is 32505858 name is "mtdblock2" rw
[    1.860000] yaffs: passed flags "inband-tags"
[    2.020000] VFS: Mounted root (yaffs2 filesystem) on device 31:2.
[    2.020000] devtmpfs: error mounting -2
[    2.030000] Freeing unused kernel memory: 160K
[    2.040000] Failed to execute /sbin/init.  Attempting defaults...
[    2.040000] Kernel panic - not syncing: No init found.  Try passing init= option to kernel. See Linux Documentation/init.txt for guidance.
[    2.040000] CPU: 0 PID: 1 Comm: swapper Not tainted 3.10.107-01388-g2c90956bcb1-dirty #15
[    2.040000] Backtrace: 
[    2.040000] [<c00122ec>] (dump_backtrace+0x0/0x108) from [<c00124fc>] (show_stack+0x18/0x1c)
[    2.040000]  r7:00000000 r6:00000000 r5:c05aa8c0 r4:c05aaec8
[    2.040000] [<c00124e4>] (show_stack+0x0/0x1c) from [<c042585c>] (dump_stack+0x20/0x28)
[    2.040000] [<c042583c>] (dump_stack+0x0/0x28) from [<c0424d0c>] (panic+0xa0/0x1f8)
[    2.040000] [<c0424c6c>] (panic+0x0/0x1f8) from [<c042460c>] (kernel_init+0x128/0x154)
[    2.040000]  r3:c065a070 r2:00000527 r1:c3603100 r0:c04d723c
[    2.040000]  r7:00000000
[    2.040000] [<c04244e4>] (kernel_init+0x0/0x154) from [<c000ef98>] (ret_from_fork+0x14/0x3c)
[    2.040000]  r5:c04244e4 r4:00000000

**Comment by junwushi** [comment]
U-Boot 2013.04-rc2-g8a5cd0c-dirty (Aug 29 2017 - 11:26:58)

CPU: NUC972
DRAM:  64 MiB
NAND:  128 MiB
MMC:   mmc: 0
*** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Net:   emac
Hit any key to stop autoboot:  0 

Loading from nand0, offset 0x200000
   Image Name:   Linux-3.10.107-01388-g2c90956bcb
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    2858992 Bytes = 2.7 MiB
   Load Address: 00007fc0
   Entry Point:  00008000
## Booting kernel from Legacy Image at 00007fc0 ...
   Image Name:   Linux-3.10.107-01388-g2c90956bcb
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    2858992 Bytes = 2.7 MiB
   Load Address: 00007fc0
   Entry Point:  00008000
   Verifying Checksum ...     0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 3.10.107-01388-g2c90956bcb1-dirty (jwshi@leo-VirtualBox) (gcc version 6.2.0 (GCC) ) #15 PREEMPT Tue Nov 14 11:43:01 CST 2017
[    0.000000] CPU: ARM926EJ-S [41069265] revision 5 (ARMv5TEJ), cr=00053177
[    0.000000] CPU: VIVT data cache, VIVT instruction cache
[    0.000000] Machine: NUC970
[    0.000000] cma: CMA: reserved 4 MiB at 03c00000
[    0.000000] Memory policy: ECC disabled, Data cache writeback
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 16256
[    0.000000] Kernel command line: noinitrd root=/dev/mtdblock2 rootfstype=yaffs2 rw rootflags=inband-tags console=ttyS0,115200n8 init=/sbin/init mem=64M lpj=744448 vt.global_cursor_default=0
[    0.000000] PID hash table entries: 256 (order: -2, 1024 bytes)
[    0.000000] Dentry cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Inode-cache hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Memory: 64MB = 64MB total
[    0.000000] Memory: 54828k/54828k available, 10708k reserved, 0K highmem
[    0.000000] Virtual kernel memory layout:
[    0.000000]     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
[    0.000000]     fixmap  : 0xfff00000 - 0xfffe0000   ( 896 kB)
[    0.000000]     vmalloc : 0xc4800000 - 0xff000000   ( 936 MB)
[    0.000000]     lowmem  : 0xc0000000 - 0xc4000000   (  64 MB)
[    0.000000]     modules : 0xbf000000 - 0xc0000000   (  16 MB)
[    0.000000]       .text : 0xc0008000 - 0xc0537ec4   (5312 kB)
[    0.000000]       .init : 0xc0538000 - 0xc0560004   ( 161 kB)
[    0.000000]       .data : 0xc0562000 - 0xc05aa8c0   ( 291 kB)
[    0.000000]        .bss : 0xc05aa8c0 - 0xc05d7a7c   ( 181 kB)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000] NR_IRQS:625
[    0.000000] sched_clock: 32 bits at 100 Hz, resolution 10000000ns, wraps every 4294967286ms
[    0.000000] Console: colour dummy device 80x30
[    0.000000] console [ttyS0] enabled
[    0.130000] Calibrating delay loop (skipped) preset value.. 148.88 BogoMIPS (lpj=744448)
[    0.140000] pid_max: default: 32768 minimum: 301
[    0.150000] Mount-cache hash table entries: 512
[    0.150000] Initializing cgroup subsys devices
[    0.160000] Initializing cgroup subsys freezer
[    0.160000] Initializing cgroup subsys perf_event
[    0.170000] CPU: Testing write buffer coherency: ok
[    0.170000] Setting up static identity map for 0xc04288e8 - 0xc0428924
[    0.180000] devtmpfs: initialized
[    0.270000] pinctrl core: initialized pinctrl subsystem
[    0.280000] NET: Registered protocol family 16
[    0.290000] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.450000] bio: create slab <bio-0> at 0
[    0.460000] SCSI subsystem initialized
[    0.470000] usbcore: registered new interface driver usbfs
[    0.480000] usbcore: registered new interface driver hub
[    0.480000] usbcore: registered new device driver usb
[    0.500000] FS-Cache: Loaded
[    0.500000] CacheFiles: Loaded
[    0.600000] NET: Registered protocol family 2
[    0.610000] TCP established hash table entries: 512 (order: 0, 4096 bytes)
[    0.620000] TCP bind hash table entries: 512 (order: -1, 2048 bytes)
[    0.630000] TCP: Hash tables configured (established 512 bind 512)
[    0.630000] TCP: reno registered
[    0.640000] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.640000] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.650000] NET: Registered protocol family 1
[    0.660000] NetWinder Floating Point Emulator V0.97 (double precision)
[    0.740000] fuse init (API version 7.22)
[    0.750000] msgmni has been set to 115
[    0.770000] NET: Registered protocol family 38
[    0.770000] Key type asymmetric registered
[    0.780000] Asymmetric key parser 'x509' registered
[    0.780000] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.790000] io scheduler noop registered
[    0.790000] io scheduler deadline registered
[    0.800000] io scheduler cfq registered (default)
[    0.810000] nuc970_dma_probe - pdev = nuc970-dma-m2m
[    0.820000] nuc970-dma nuc970-dma-m2m: NUC970 M2M DMA ready
[    0.850000] nuc970-uart.0: ttyS0 at I/O 0x0 (irq = 36) is a NUC970
[    0.860000] nuc970-uart.1: ttyS1 at I/O 0x0 (irq = 37) is a NUC970
[    0.870000] nuc970-uart.2: ttyS2 at I/O 0x0 (irq = 38) is a NUC970
[    0.880000] nuc970-uart.3: ttyS3 at I/O 0x0 (irq = 43) is a NUC970
[    0.890000] nuc970-uart.5: ttyS5 at I/O 0x0 (irq = 44) is a NUC970
[    0.900000] nuc970-uart.6: ttyS6 at I/O 0x0 (irq = 40) is a NUC970
[    0.900000] nuc970-uart.8: ttyS8 at I/O 0x0 (irq = 41) is a NUC970
[    0.910000] nuc970-uart.10: ttyS10 at I/O 0x0 (irq = 42) is a NUC970
[    0.920000] nuc970_dma_proxy module initialized
[    0.960000] loop: module loaded
[    0.960000] nbd: registered device at major 43
[    1.020000] SCSI Media Changer driver v0.25 
[    1.030000] nuc970 mtd nand driver version: 20160331
[    1.030000] NAND device: Manufacturer ID: 0xef, Chip ID: 0xf1 (Winbond NAND 128MiB 3,3V 8-bit), 128MiB, page size: 2048, OOB size: 64
[    1.040000] nand: SMRA size 40, 32
[    1.050000] Bad block table not found for chip 0
[    1.050000] Bad block table not found for chip 0
[    1.060000] Scanning device for bad blocks
[    1.110000] Bad block table written to 0x000007fe0000, version 0x01
[    1.120000] Bad block table written to 0x000007fc0000, version 0x01
[    1.120000] Creating 3 MTD partitions on "nand0":
[    1.130000] 0x000000000000-0x000000200000 : "u-boot"
[    1.140000] 0x000000200000-0x000000a00000 : "Kernel"
[    1.150000] 0x000000a00000-0x000008000000 : "user"
[    1.160000] fmi-sm: registered successfully! mtdid=nand0
[    1.170000] tun: Universal TUN/TAP device driver, 1.6
[    1.180000] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[    1.200000] libphy: nuc970_rmii0: probed
[    1.200000] PPP generic driver version 2.4.2
[    1.210000] PPP BSD Compression module registered
[    1.220000] PPP Deflate Compression module registered
[    1.220000] PPP MPPE Compression module registered
[    1.230000] NET: Registered protocol family 24
[    1.230000] PPTP driver version 0.8.5
[    1.240000] SLIP: version 0.8.4-NET3.019-NEWTTY (dynamic channels, max=256).
[    1.240000] CSLIP: code copyright 1989 Regents of the University of California.
[    1.250000] ieee802154hardmac ieee802154hardmac: Added ieee802154 HardMAC hardware
[    1.270000] ieee802154fakelb ieee802154fakelb: added ieee802154 hardware
[    1.270000] usbcore: registered new interface driver cdc_ether
[    1.280000] usbcore: registered new interface driver net1080
[    1.290000] usbcore: registered new interface driver cdc_subset
[    1.300000] usbcore: registered new interface driver cdc_ncm
[    1.300000] usbcore: registered new interface driver qmi_wwan
[    1.310000] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    1.320000] ehci_nuc970_probe() - name: nuc970-ehci
[    1.320000] nuc970-ehci nuc970-ehci: Nuvoton NUC970 EHCI Host Controller
[    1.330000] nuc970-ehci nuc970-ehci: new USB bus registered, assigned bus number 1
[    1.340000] nuc970-ehci nuc970-ehci: irq 23, io mem 0xb0005000
[    1.370000] nuc970-ehci nuc970-ehci: USB 2.0 started, EHCI 0.95
[    1.370000] hub 1-0:1.0: USB hub found
[    1.380000] hub 1-0:1.0: 2 ports detected
[    1.380000] ehci-platform: EHCI generic platform driver
[    1.390000] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    1.400000] nuc970-ohci nuc970-ohci: Nuvoton NUC970 OHCI Host Controller
[    1.400000] nuc970-ohci nuc970-ohci: new USB bus registered, assigned bus number 2
[    1.410000] nuc970-ohci nuc970-ohci: irq 24, io mem 0xb0007000
[    1.480000] hub 2-0:1.0: USB hub found
[    1.480000] hub 2-0:1.0: 2 ports detected
[    1.490000] usbcore: registered new interface driver cdc_acm
[    1.500000] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters
[    1.510000] usbcore: registered new interface driver usblp
[    1.510000] usbcore: registered new interface driver cdc_wdm
[    1.520000] usbcore: registered new interface driver usb-storage
[    1.530000] usbcore: registered new interface driver usbserial
[    1.530000] usbcore: registered new interface driver option
[    1.540000] usbserial: USB Serial support registered for GSM modem (1-port)
[    1.550000] g_serial gadget: Gadget Serial v2.4
[    1.560000] g_serial gadget: g_serial ready
[    1.560000] ==================================1
[    1.570000] nuc970adc_probe - pdev = nuc970-adc
[    1.590000] nuc970-rtc nuc970-rtc: rtc core: registered nuc970-rtc as rtc0
[    1.600000] leds-gpio leds-gpio: pins are not configured from the driver
[    1.610000] ledtrig-cpu: registered to indicate activity on CPUs
[    1.640000] NUC970 Crypto engine enabled.
[    1.640000] NET: Registered protocol family 26
[    1.650000] ipip: IPv4 over IPv4 tunneling driver
[    1.660000] gre: GRE over IPv4 demultiplexor driver
[    1.660000] IPv4 over IPSec tunneling driver
[    1.670000] TCP: cubic registered
[    1.670000] Initializing XFRM netlink socket
[    1.680000] NET: Registered protocol family 10
[    1.700000] mip6: Mobile IPv6
[    1.700000] ip6_tables: (C) 2000-2006 Netfilter Core Team
[    1.710000] sit: IPv6 over IPv4 tunneling driver
[    1.720000] ip6_gre: GRE over IPv6 tunneling driver
[    1.730000] NET: Registered protocol family 17
[    1.730000] NET: Registered protocol family 15
[    1.740000] Bridge firewalling registered
[    1.740000] Ebtables v2.0 registered
[    1.740000] l2tp_core: L2TP core driver, V2.0
[    1.750000] l2tp_ppp: PPPoL2TP kernel driver, V2.0
[    1.750000] l2tp_ip: L2TP IP encapsulation support (L2TPv3)
[    1.760000] l2tp_netlink: L2TP netlink interface
[    1.760000] l2tp_eth: L2TP ethernet pseudowire support (L2TPv3)
[    1.770000] l2tp_ip6: L2TP IP encapsulation support for IPv6 (L2TPv3)
[    1.780000] DCCP: Activated CCID 2 (TCP-like)
[    1.790000] DCCP: Activated CCID 3 (TCP-Friendly Rate Control)
[    1.800000] sctp: Hash tables configured (established 2048 bind 4096)
[    1.810000] NET: Registered protocol family 21
[    1.820000] Registered RDS/tcp transport
[    1.820000] NET: Registered protocol family 36
[    1.830000] Key type dns_resolver registered
[    1.840000] Key type encrypted registered
[    1.850000] nuc970-rtc nuc970-rtc: setting system clock to 2017-02-14 09:34:07 UTC (1487064847)
[    1.860000] yaffs: dev is 32505858 name is "mtdblock2" rw
[    1.860000] yaffs: passed flags "inband-tags"
[    2.020000] VFS: Mounted root (yaffs2 filesystem) on device 31:2.
[    2.020000] devtmpfs: error mounting -2
[    2.030000] Freeing unused kernel memory: 160K
[    2.040000] Failed to execute /sbin/init.  Attempting defaults...
[    2.040000] Kernel panic - not syncing: No init found.  Try passing init= option to kernel. See Linux Documentation/init.txt for guidance.
[    2.040000] CPU: 0 PID: 1 Comm: swapper Not tainted 3.10.107-01388-g2c90956bcb1-dirty #15
[    2.040000] Backtrace: 
[    2.040000] [<c00122ec>] (dump_backtrace+0x0/0x108) from [<c00124fc>] (show_stack+0x18/0x1c)
[    2.040000]  r7:00000000 r6:00000000 r5:c05aa8c0 r4:c05aaec8
[    2.040000] [<c00124e4>] (show_stack+0x0/0x1c) from [<c042585c>] (dump_stack+0x20/0x28)
[    2.040000] [<c042583c>] (dump_stack+0x0/0x28) from [<c0424d0c>] (panic+0xa0/0x1f8)
[    2.040000] [<c0424c6c>] (panic+0x0/0x1f8) from [<c042460c>] (kernel_init+0x128/0x154)
[    2.040000]  r3:c065a070 r2:00000527 r1:c3603100 r0:c04d723c
[    2.040000]  r7:00000000
[    2.040000] [<c04244e4>] (kernel_init+0x0/0x154) from [<c000ef98>] (ret_from_fork+0x14/0x3c)
[    2.040000]  r5:c04244e4 r4:00000000

**Comment by yachen** [comment]
Hi,

We're unable to reproduce this problem. 
Did you program the yaffs2 partition to NAND flash by U-Boot or NuWriter?
If you restore the kernel image (with previous NAND driver), it can mount this MTP partition without problem?

Sincerely,

Yi-An Chen

**Comment by yachen** [comment]
Hi,

Did you set power on setting about ECC and page size?


Sincerely,

Yi-An Chen

**Comment by junwushi** [comment]
cfg9 and cfg8 dip are all off? how does setting it?

**Comment by junwushi** [comment]
i am setting PA6-P9 all off ,it is working, others failed.

**Comment by yachen** [comment]
Hi,

For the Winbond NAND 128MiB 3,3V 8-bit flash you used, please set PA6~PA9 as OFF.
In path 2c90956,  we updated NAND driver to use power on setting to overwrite the flash type found by kernel. So since this flash can be identified by kernel alright, you should set PA6~PA9 as OFF.

Sincerely,

Yi-An Chen
