### ISSUE TITLE
usb gadget with cdc ethernet not work

### ISSUE THREAD

**Issue by junwushi** [OpenNuvoton/NUC970_Linux_Kernel#2]
rndis feature is not work,  show linux USB Ehternet/RNDIS gadget #4 in window device tree ,but it is with "！“，does not work.

**Comment by junwushi** [comment]
if building kernel with usb gadget->serial gadget(with cdc acm and cdc obex support), the serial comport device will often not work,many times reboot the linux device ,the comport device will work in window xp/10.

**Comment by yachen** [comment]
Hi @junwushi ,

We are aware of the RNDIS issue and have engineer checking it now.
Can you provide us your kernel config for CDC issue? We've test it before and have other customers using it but didn't see the issue you report. Thanks. 

Sincerely,

Yi-An Chen

**Comment by junwushi** [comment]
Dear Chen,
    i am already upload my .config,please remove the extension ".zip" and  decompress it with TAR.
[config.tar.zip](https://github.com/OpenNuvoton/NUC970_Linux_Kernel/files/819978/config.tar.zip)

**Comment by yachen** [comment]
Hi @junwushi ,

I'm able to reproduce the CDC unstable issue and have forwarded the issue to the engineer who maintain the NUC970 gadget driver. Will update the fix to Github as soon as it's fixed.


Sincerely,

Yi-An Chen

**Comment by yachen** [comment]
Hi @junwushi ,

Please check if commit c1a9947108e2929c7621f7b91fa3aaf4d586b1eb fix CDC issue or not.
RNDIS issue is still under investigating.


Sincerely,

Yi-An Chen

**Comment by junwushi** [comment]
rndis still not work, device driver install  normal,but network device always show in disable status,can't enable even you maunul enable it. the attach is the rndis driver for windows.
[linux.rar.zip](https://github.com/OpenNuvoton/NUC970_Linux_Kernel/files/854522/linux.rar.zip)

**Comment by yachen** [comment]
Hi @junwushi ,

This patch is intent for fix the "usb gadget->serial gadget serial comport device will often not work" issue you reported. Please let us know if this fixed the CDC issue.  Thanks.
We're still working on the RNDIS issue and will push to this repository after it's fixed.

Sincerely,

Yi-An Chen

**Comment by junwushi** [comment]
yes, the CDC seems stable,will observe it longer time.

**Comment by junwushi** [comment]
I think cdc issue not sloved.
1.after I update  the c1a9947  the system often crashed, not show any crash information in debug, only hang up. and sometimes the sytem is startup ok, below is the debug message when the system hangup . but it is not hang up before update.
Starting kernel ...

Uncompressing Li done, booting t[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 3.10.1011+ (jwshi@leo-VirtualBox) (gcc version 6.2.0 (GCC) ) #72 PREEMPT Tue Mar 21 19:44:53 CST 2017
[    0.000000] CPU: ARM926EJ-S [41069265] revision 5 (ARMv5TEJ), cr=00053177
[    0.000000] CPU: VIVT data cache, VIVT instruction cache
[    0.000000] Machine: NUC970
[    0.000000] cma: CMA: reserved 4 MiB at 03c00000
[    0.000000] Memory policy: ECC disabled, Data cache writeback
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 16256
[    0.000000] Kernel command line: noinitrd root=/dev/mtdblock2 rootfstype=yaffs2 rw rootflags=inband-tags console=ttyS0,115200n8 init=/sbin/init mem=64M lpj=744448 vt.global_cursor_default=0
[    0.000000] PID hash table entries: 256 (order: -2, 1024 bytes)
[    0.000000] Dentry cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Inode-cache hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Memory: 64MB = 64MB total
[    0.000000] Memory: 55448k/55448k available, 10088k reserved, 0K highmem
[    0.000000] Virtual kernel memory layout:
[    0.000000]     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
[    0.000000]     fixmap  : 0xfff00000 - 0xfffe0000   ( 896 kB)
[    0.000000]     vmalloc : 0xc4800000 - 0xff000000   ( 936 MB)
[    0.000000]     lowmem  : 0xc0000000 - 0xc4000000   (  64 MB)
[    0.000000]     modules : 0xbf000000 - 0xc0000000   (  16 MB)
[    0.000000]       .text : 0xc0008000 - 0xc04a9f64   (4744 kB)
[    0.000000]       .init : 0xc04aa000 - 0xc04ce930   ( 147 kB)
[    0.000000]       .data : 0xc04d0000 - 0xc0514400   ( 273 kB)
[    0.000000]        .bss : 0xc0514400 - 0xc053c8cc   ( 162 kB)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000] NR_IRQS:625
[    0.000000] sched_clock: 32 bits at 100 Hz, resolution 10000000ns, wraps every 4294967286ms
[    0.000000] Console: colour dummy device 80x30
[    0.000000] console [ttyS0] enabled
[    0.140000] Calibrating delay loop (skipped) preset value.. 148.88 BogoMIPS (lpj=744448)
[    0.150000] pid_max: default: 32768 minimum: 301
[    0.150000] Mount-cache hash table entries: 512
[    0.160000] Initializing cgroup subsys devices
[    0.170000] Initializing cgroup subsys freezer
[    0.170000] Initializing cgroup subsys perf_event
[    0.170000] CPU: Testing write buffer coherency: ok
[    0.180000] Setting up static identity map for 0xc03ac570 - 0xc03ac5c8
[    0.190000] devtmpfs: initialized
[    0.280000] pinctrl core: initialized pinctrl subsystem
[    0.290000] NET: Registered protocol family 16
[    0.300000] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.480000] bio: create slab <bio-0> at 0
[    0.490000] SCSI subsystem initialized
[    0.500000] usbcore: registered new interface driver usbfs
[    0.500000] usbcore: registered new interface driver hub
[    0.510000] usbcore: registered new device driver usb
[    0.520000] i2c_gpio_probe - pdev = i2c-gpio
[    0.520000] platform i2c-gpio.2: Driver i2c-gpio requests probe deferral
[    0.530000] pps_core: LinuxPPS API ver. 1 registered
[    0.540000] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.550000] PTP clock support registered
[    0.560000] FS-Cache: Loaded
[    0.560000] CacheFiles: Loaded
[    0.670000] NET: Registered protocol family 2
[    0.680000] TCP established hash table entries: 512 (order: 0, 4096 bytes)
[    0.690000] TCP bind hash table entries: 512 (order: -1, 2048 bytes)
[    0.700000] TCP: Hash tables configured (established 512 bind 512)
[    0.700000] TCP: reno registered
[    0.710000] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.710000] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.720000] NET: Registered protocol family 1
[    0.720000] NetWinder Floating Point Emulator V0.97 (double precision)
[    0.810000] fuse init (API version 7.22)
[    0.820000] msgmni has been set to 116
[    0.830000] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 250)
[    0.840000] io scheduler noop registered
[    0.840000] io scheduler deadline registered
[    0.850000] io scheduler cfq registered (default)
[    0.860000] [nuc970fb_probe] 20
[    0.890000] Console: switching to colour frame buffer device 60x17
[    0.910000] fb0: nuc970fb frame buffer device
[    0.920000] nuc970_dma_probe - pdev = nuc970-dma-m2m
[    0.920000] nuc970-dma nuc970-dma-m2m: NUC970 M2M DMA ready
[    0.960000] nuc970-uart.0: ttyS0 at I/O 0x0 (irq = 36) is a NUC970
[    0.970000] nuc970-uart.1: ttyS1 at I/O 0x0 (irq = 37) is a NUC970
[    0.980000] nuc970-uart.2: ttyS2 at I/O 0x0 (irq = 38) is a NUC970
[    0.990000] nuc970-uart.3: ttyS3 at I/O 0x0 (irq = 43) is a NUC970
[    0.990000] nuc970-uart.5: ttyS5 at I/O 0x0 (irq = 44) is a NUC970
[    1.000000] nuc970-uart.6: ttyS6 at I/O 0x0 (irq = 40) is a NUC970
[    1.010000] nuc970-uart.8: ttyS8 at I/O 0x0 (irq = 41) is a NUC970
[    1.020000] nuc970-uart.10: ttyS10 at I/O 0x0 (irq = 42) is a NUC970
[    1.040000] nuc970_dma_proxy module initialized
[    1.040000] [drm] Initialized drm 1.1.0 20060810
[    1.060000] loop: module loaded
[    1.060000] nbd: registered device at major 43
[    1.130000] SCSI Media Changer driver v0.25 
[    1.140000] nuc970 mtd nand  driver version: 20160331
[    1.150000] ONFI param page 0 valid
[    1.150000] ONFI flash detected
[    1.160000] NAND device: Manufacturer ID: 0x01, Chip ID: 0xdc (AMD/Spansion S34ML04G2), 512MiB, page size: 2048, OOB size: 128
[    1.170000] SYSTEM:  USE     BCH_T4 HWECC algorithm(SMRA     size: 64, Parity number:32 bytes)
[    1.180000] EXECUTE: USE BCH_T4      HWECC algorithm(SMRA size: 64, Parity number:32 bytes)
[    1.180000] USE      BCH_T4 HWECC algorithm(Parity number:32 bytes)
[    1.190000] Bad block table found at page 262080, version 0x01
[    1.200000] Bad block table found at page 262016, version 0x01
[    1.200000] Creating 3 MTD partitions on "nand0":
[    1.210000] 0x000000000000-0x000000200000 : "u-boot"
[    1.220000] 0x000000200000-0x000000a00000 : "Kernel"
[    1.230000] 0x000000a00000-0x000020000000 : "user"
[    1.250000] fmi-sm:  registered successfully! mtdid=nand0
[    1.250000] tun: Universal TUN/TAP device driver, 1.6
[    1.260000] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[    1.270000] libphy: nuc970_rmii0: probed
[    1.280000] nuc970-emac0 nuc970-emac0: phy_find_first() failed
[    1.290000] nuc970-emac0 nuc970-emac0: nuc970_mii_setup err
[    1.290000] PPP generic driver version 2.4.2
[    1.300000] PPP BSD Compression module registered
[    1.300000] PPP Deflate Compression module registered
[    1.310000] PPP MPPE Compression module registered
[    1.310000] NET: Registered protocol family 24
[    1.320000] SLIP: version 0.8.4-NET3.019-NEWTTY (dynamic channels, max=256).
[    1.330000] CSLIP: code copyright 1989 Regents of the University of California.
[    1.330000] hdlc: HDLC support module revision 1.22
[    1.340000] ieee802154hardmac ieee802154hardmac: Added ieee802154 HardMAC hardware
[    1.360000] ieee802154fakelb ieee802154fakelb: added ieee802154 hardware
[    1.360000] usbcore: registered new interface driver rtl8150
[    1.370000] usbcore: registered new interface driver r8152
[    1.380000] usbcore: registered new interface driver cdc_ether
[    1.380000] usbcore: registered new interface driver cdc_eem
[    1.390000] usbcore: registered new interface driver rndis_host
[    1.400000] usbcore: registered new interface driver cdc_ncm
[    1.410000] usbcore: registered new interface driver cdc_mbim
[    1.410000] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    1.420000] ehci_nuc970_probe() - name: nuc970-ehci
[    1.430000] nuc970-ehci nuc970-ehci: Nuvoton NUC970 EHCI Host Controller
[    1.430000] nuc970-ehci nuc970-ehci: new USB bus registered, assigned bus number 1
[    1.440000] nuc970-ehci nuc970-ehci: irq 23, io mem 0xb0005000
[    1.470000] nuc970-ehci nuc970-ehci: USB 2.0 started, EHCI 0.95
[    1.470000] hub 1-0:1.0: USB hub found
[    1.480000] hub 1-0:1.0: 2 ports detected
[    1.490000] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    1.490000] nuc970-ohci nuc970-ohci: Nuvoton NUC970 OHCI Host Controller
[    1.500000] nuc970-ohci nuc970-ohci: new USB bus registered, assigned bus number 2
[    1.510000] nuc970-ohci nuc970-ohci: irq 24, io mem 0xb0007000
[    1.570000] hub 2-0:1.0: USB hub found
[    1.570000] hub 2-0:1.0: 2 ports detected
[    1.580000] usbcore: registered new interface driver cdc_wdm
[    1.590000] g_serial gadget: Gadget Serial v2.4
[    1.600000] g_serial gadget: g_serial ready
[    1.610000] mousedev: PS/2 mouse device common for all mice
[    1.610000] nuc970adc_probe - pdev = nuc970-adc
[    1.640000] nuc970-rtc nuc970-rtc: rtc core: registered nuc970-rtc as rtc0
[    1.640000] i2c /dev entries driver
[    1.650000] cpuidle: using governor ladder
[    1.680000] NUC970 Crypto engine enabled.
[    1.680000] hidraw: raw HID events driver (C) Jiri Kosina
[    1.690000] usbcore: registered new interface driver usbhid
[    1.700000] usbhid: USB HID core driver
[    1.700000] NET: Registered protocol family 26
[    1.710000] ipip: IPv4 over IPv4 tunneling driver
[    1.720000] IPv4 over IPSec tunneling driver
[    1.730000] TCP: cubic registered
[    1.740000] NET: Registered protocol family 10
[    1.750000] mip6: Mobile IPv6
[    1.750000] sit: IPv6 over IPv4 tunneling driver
[    1.760000] ip6_gre: GRE over IPv6 tunneling driver
[    1.770000] NET: Registered protocol family 17
[    1.780000] NET: Registered protocol family 15
[    1.780000] Bridge firewalling registered
[    1.790000] l2tp_core: L2TP core driver, V2.0
[    1.790000] l2tp_ppp: PPPoL2TP kernel driver, V2.0
[    1.800000] l2tp_ip: L2TP IP encapsulation support (L2TPv3)
[    1.800000] l2tp_netlink: L2TP netlink interface
[    1.810000] l2tp_eth: L2TP ethernet pseudowire support (L2TPv3)
[    1.810000] l2tp_ip6: L2TP IP encapsulation support for IPv6 (L2TPv3)
[    1.820000] NET: Registered protocol family 36
[    1.840000] g_serial gadget: high-speed config #2: CDC ACM config
[    1.850000] Key type encrypted registered
[    1.850000] i2c_gpio_probe - pdev = i2c-gpio
[    2.160000] input: ft5x0x_ts as /devices/platform/i2c-gpio.2/i2c-2/2-0038/input/input0
[    2.330000] ft5x0x_ts 2-0038: Screen size: 480X272 initialized:  IRQ pin 174 ==> 430, Reset pin 173.
[    2.340000] i2c-gpio i2c-gpio.2: using pins 193 (SDA) and 192 (SCL)
[    2.340000] nuc970-rtc nuc970-rtc: setting system clock to 2016-10-26 12:58:16 UTC (1477486696)
[    2.350000] yaffs: dev is 32505858 name is "mtdblock2" rw
[    2.360000] yaffs: passed flags "inband-tags"
[    5.590000] VFS: Mounted root (yaffs2 filesystem) on device 31:2.
[    5.600000] devtmpfs: mounted
[    5.600000] Freeing unused kernel memory: 144K (c04aa000 - c04ce000)
INIT: version 2.88 bootin
Starting udev
[    6.750000] udevd[669]: starting version 3.2
[    6.880000] udevd[670]: starting eudev-3.2

2.when the sytem up, login console, then reconnect the usb cable, will effect console rs232 port and ,console will not response any type, after a long time console display blow:
[    32.4000000]ttyS0: 1 input overrubs(s)
>
>
>
>

**Comment by junwushi** [comment]
the issue is still there, usually all seems ok(device is ok, port is ready). but just can't comunicate,type any char not response in ttyGS0(getty). after reboot many times ,it is restore working. why?

**Comment by yachen** [comment]
Hi @junwushi ,

May I know how do you test the ttyGS0? I'm testing with putty on my Windows machine and cannot reproduce the problem so far.


Sincerely,

Yi-An Chen

**Comment by junwushi** [comment]
if application  open the ttyGS0 ,then  disconnect the usb cable,the ttyGS0 device lost in linux,but the application  maybe hang that still  perform some function of the device ttyGS0 (like selct() etc.). and  window side does not know the comport is invalid,  not received any notify for disconnect.

**Comment by junwushi** [comment]
other thing,the battery adc reference voltage use  #define INTERNAL_VALTAGE 2500 in bsp adc driver,but use 3300 is corrent ADC data result in fact . why? please confirm my supcisions are corrent? i am not sure,and the program  guide docment is so simple.

**Comment by schung1218** [comment]
Hi @junwushi 
The battery voltage detection select internal voltage(2.5v)  or external reference pin.
if the external reference pin connect 3.3v, use 3300 is correct.
if the external reference pin is floating , use 2500 is correct.

**Comment by junwushi** [comment]
sometime hang in udc drive line:
while ((_raw_read(comtroller.reg + REG_USBD_IRQ_STAT) &0x20 )==0 );
when if you muilttime plus on/off the cable and reopen ttyGS0 for comunucation.

**Comment by junwushi** [comment]
and I found the USB_FLT_DET irq never execute,not print plug in and un plug  message in console.

**Comment by yachen** [comment]
@junwushi ,

What board are you testing? "USB_FLT_DET irq never execute" should be hardware issue.

Sincerely,

Yi-An Chen

**Comment by junwushi** [comment]
it is host&device otg mode, the ph0 pin always high voltage,becase usb VCC it is connect battery. how to design usb0 in otg mode and ph0 can indentify device plug in and off?

**Comment by yachen** [comment]
Hi @junwushi ,

Are you using Nuvoton's DEV board? If so, please set SW34:1 to OFF position and change R83 to 20K Ohm, R84 to 39K Ohm.

Sincerely,

Yi-An Chen

**Comment by junwushi** [comment]
after update kernal 107,there are cdc serial report below message:

gateway /dev/ttyS0

gateway login: [   14.310000] g_serial gadget: high-speed config #2: CDC ACM config
Hangup
root
root@gateway:~# [   19.430000] g_serial gadget: high-speed config #2: CDC ACM config
Hangup
[   20.210000] g_serial gadget: high-speed config #2: CDC ACM config
Hangup
[   28.510000] g_serial gadget: high-speed config #2: CDC ACM config
Hangup
[   35.940000] g_serial gadget: high-speed config #2: CDC ACM config
Hangup
[   54.930000] g_serial gadget: high-speed config #2: CDC ACM config
Hangup

**Comment by junwushi** [comment]
please this function "static u32 udc_transfer(struct nuc970_ep *ep, u8* buf, size_t size, u32 mode)" in nuc970_udc.c, the function always return 0, it is right?

**Comment by junwushi** [comment]
my device usually die and show  the "hangup1" that add by my self for debug ,why? 

write_packet(struct nuc970_ep *ep, struct nuc970_request *req)
{
	struct nuc970_udc *udc = &controller;
	unsigned len, tmp;
	u8  *buf;
	u32 data, i;
	u32 max;

	buf = req->req.buf + req->req.actual;
	prefetch(buf);
//	if (udc->gadget.speed == USB_SPEED_FULL)
//		udelay(500);

	if (ep->ep_num == 0)
	{ //ctrl pipe don't use DMA
		max = ep->ep.maxpacket;
		len = min(req->req.length - req->req.actual, max);

		if (len == 0)
		{
			if (req->req.zero&&!req->req.length)
				__raw_writel(CEP_ZEROLEN, controller.reg + REG_USBD_CEP_CTRL_STAT);
		}
		else
		{
			i=0;
			while ((__raw_readl(controller.reg + REG_USBD_CEP_IRQ_STAT) & 0x1000) != 0x1000)
			{
				i++;
				if (i>10000) printk("hang up1\r\n");
			}
				;

**Comment by yachen** [comment]
Hi @junwushi ,

The loop is waiting for previous transfer to complete. Shouldn't stuck there. Did you make other modification as well?
Anyway, please pull latest driver, we fixed some issues including the udc_transfer() always return 0 you reported.


Sincerely,

Yi-An Chen

**Comment by junwushi** [comment]
the udc_transfer() always return 0 maybe right, becase i check that code in the dma irq process to increase the count. so don't need return send bytes.
the last code i am checking

**Comment by junwushi** [comment]
"udc_transfer() always return 0" is not issue, please change back it, that is right, now test the new code ,that not working, and change back  udc_transfer()  return 0 that working.

**Comment by yachen** [comment]
Hi @junwushi ,

Updated, please pull again. Many thanks for the feedback.


Sincerely,

Yi-An Chen

**Comment by junwushi** [comment]
ok, working

**Comment by junwushi** [comment]
still same issue in udc driver. write_packet only die in while {} section and wait for every time.
other things, below code, first unlock and then lock is right?
static void nuke (struct nuc970_udc *udc, struct nuc970_ep *ep)
{
	while (!list_empty (&ep->queue))
	{
		struct nuc970_request *req;
		req = list_entry (ep->queue.next, struct nuc970_request, queue);
		list_del_init (&req->queue);
		req->req.status = -ESHUTDOWN;
		spin_unlock (&udc->lock);
		req->req.complete (&ep->ep, &req->req);
		spin_lock (&udc->lock);
	}
}

**Comment by junwushi** [comment]
now i used the USB cable that maybe not good, and then print below message cycle:
[  309.680000] g_serial gadget: high-speed config #2: CDC ACM config
[  414.200000] g_serial gadget: high-speed config #2: CDC ACM config
[  416.310000] g_serial gadget: high-speed config #2: CDC ACM config
[  438.370000] g_serial gadget: high-speed config #2: CDC ACM config
[  442.360000] g_serial gadget: high-speed config #2: CDC ACM config
[  452.400000] g_serial gadget: high-speed config #2: CDC ACM config
[  484.570000] g_serial gadget: high-speed config #2: CDC ACM config
[  528.790000] g_serial gadget: high-speed config #2: CDC ACM config
[  530.830000] g_serial gadget: high-speed config #2: CDC ACM config
[  534.840000] g_serial gadget: high-speed config #2: CDC ACM config
[  536.830000] g_serial gadget: high-speed config #2: CDC ACM config
[  657.340000] g_serial gadget: high-speed config #2: CDC ACM config
[  657.600000] g_serial gadget: high-speed config #2: CDC ACM config
[  657.870000] g_serial gadget: high-speed config #2: CDC ACM config
[  673.170000] g_serial gadget: high-speed config #2: CDC ACM config
[  673.450000] g_serial gadget: high-speed config #2: CDC ACM config
[  673.730000] g_serial gadget: high-speed config #2: CDC ACM config
[  699.050000] g_serial gadget: high-speed config #2: CDC ACM config
[  699.310000] g_serial gadget: high-speed config #2: CDC ACM config
[  764.210000] g_serial gadget: high-speed config #2: CDC ACM config
[  764.470000] g_serial gadget: high-speed config #2: CDC ACM config
[  789.890000] hangup1!
[  799.800000] g_serial gadget: high-speed config #2: CDC ACM config
[  800.040000] g_serial gadget: high-speed config #2: CDC ACM config
[  800.330000] g_serial gadget: high-speed config #2: CDC ACM config
[  800.580000] g_serial gadget: high-speed config #2: CDC ACM config
[  800.870000] g_serial gadget: high-speed config #2: CDC ACM config
[  801.170000] g_serial gadget: high-speed config #2: CDC ACM config

**Comment by yachen** [comment]
We think the lock/unlock could be removed in nuke(). Will do some more test before release update.

**Comment by junwushi** [comment]
new issuse:
i connect the 3g module in usb port, it is show below error,and i am be care of to check hardware, not found any problem:

[    2.710000] usb 2-2: new low-speed USB device number 2 using nuc970-ohci
[    2.900000] usb 2-2: device descriptor read/64, error -62
[    3.190000] usb 2-2: device descriptor read/64, error -62
[    3.480000] usb 2-2: new low-speed USB device number 3 using nuc970-ohci
[    3.670000] usb 2-2: device descriptor read/64, error -62
[    3.960000] usb 2-2: device descriptor read/64, error -62
[    4.250000] usb 2-2: new low-speed USB device number 4 using nuc970-ohci

**Comment by yachen** [comment]
Hi @junwushi ,

This is a USB signal quality issue. We have other customer's hardware got same error.
First the dongle was misidentified as low speed device, and then driver report error -62.


Sincerely,

Yi-An Chen

**Comment by yachen** [comment]
Hi @junwushi ,

Please pull 737c84e and see if it fix the write_packet() loop forever issue.
We saw similar issue while connecting with some PC, and this patch fixed it.

Sincerely,

Yi-An Chen

**Comment by yachen** [comment]
Close unless there's further discussion on this issue.

**Comment by swex** [comment]
ethernet/RNDIS still not working, any update on this?
