### ISSUE TITLE
Does NUC970 Linux Kernel Support PREEMPT RT patch ?

### ISSUE THREAD

**Issue by technoelinux** [OpenNuvoton/NUC970_Linux_Kernel#21]
HI,
I'm working on NuMaker Tomato board for industrial application. I need to know whether NUC970_Linux_Kernel supports PREEMPT RT patch or other Realtime Support for this kernel.
Thanks.

**Comment by yachen** [comment]
Not sure. We haven't test PREEMPT RT or other real time solution before.


Sincerely,

Yi-An Chen
