### ISSUE TITLE
NUC970 EMAC issue

### ISSUE THREAD

**Issue by morway** [OpenNuvoton/NUC970_Linux_Kernel#25]
Hi, I have a problem with the driver of ethernet. I want to receive the socket larger than 1514 Bytes one time because I saw the code seperate the socket when it is larger than 1514 Bytes. Is there some way to do it?Thanks!

**Comment by yachen** [comment]
Hi,

Try
+ #define MCMDR_ALP		(0x01 << 1)

-val |= MCMDR_SPCRC | /*MCMDR_ENMDC |*/ MCMDR_ACP /*| ENMDC*/;
+val |= MCMDR_SPCRC | MCMDR_ACP | MCMDR_ALP;
+__raw_writel(<PKT_LEN>,  REG_DMARFC); // PKT_LEN  = Max Rx packet length - 4 byte CRC.

-if (likely((status & RXDS_RXGD) && (length <= 1514))) {
+if (likely(status & RXDS_RXGD)) {


Sincerely,

Yi-An Chen

**Comment by yachen** [comment]
Close since no further feedback.
