### ISSUE TITLE
Upgrade to 3.18

### ISSUE THREAD

**Issue by ponyatov** [OpenNuvoton/NUC970_Linux_Kernel#26]
Good day

Does anybody work on an upgrade to last 3.18 version?

(I need patched functionality in PPS time sync from latest kernel releases)

**Comment by yachen** [comment]
Hi,

We do not have plan to update kernel version for NUC970.


Sincerely,

Yi-An Chen

**Comment by ponyatov** [comment]
Why you stop support?

**Comment by parrotgeek1** [comment]
You could try backporting the commits.

**Comment by yachen** [comment]
As there's no plan to upgrade to 3.18, close this issue.
