### ISSUE TITLE
strange u-boot behaviour on nuc976

### ISSUE THREAD

**Issue by ponyatov** [OpenNuvoton/NUC970_Linux_Kernel#27]
`U-Boot 2013.04-rc2`

release v1.5-nuc970.tar.gz
make nuc976_defconfig

CPU: NUC976
DRAM:  64 MiB
MMC:   mmc: 0
SF: Detected MX25L12805D with page size 64 KiB, total 16 MiB
In:    serial
Out:   serial
Err:   serial
Net:   emac
Hit any key to stop autoboot:  0 
U-Boot> bootp 0x200000
BOOTP broadcast 1
DHCP client bound to address 192.168.63.97
Using emac device
TFTP from server 192.168.63.61; our IP address is 192.168.63.97
Filename 'uImage'.
Load address: 0x200000
Loading: #################################################################
         ############################################################
         2.1 MiB/s
done
Bytes transferred = 1827112 (1be128 hex)
U-Boot> bootm 0x200000
'## Booting kernel from Legacy Image at 00200000 ...'
   Image Name:   Linux kernel
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    1827048 Bytes = 1.7 MiB
   Load Address: 80008000
   Entry Point:  80008000
   Verifying Checksum ... OK
SF: Detected MX25L12805D with page size 64 KiB, total 16 MiB
   Loading Kernel Image ... OK
OK
  
Starting kernel ...

Uncompressing Li

**Comment by ponyatov** [comment]
U-Boot 2013.04-rc2 (Dec 05 2017 - 14:49:18)

CPU: NUC976
DRAM:  64 MiB
MMC:   mmc: 0
SF: Detected MX25L12805D with page size 64 KiB, total 16 MiB
In:    serial
Out:   serial
Err:   serial
Net:   emac
Hit any key to stop autoboot:  0 
U-Boot> 
U-Boot> 
U-Boot> printenv
baudrate=115200
bootargs=console=ttyS0,115200n8
bootcmd=sf probe; sf read 0x200000 0x50000 0x1b0000; bootm 0x200000
bootdelay=3
bootfile=uImage
botargs=console=ttyS0,115200n8 root=/dev/mtdblock4 ro rootfstype=sqashfs
delenv=env default -a -f; saveenv
earlycon=smh
ethact=emac
ethaddr=00:00:00:11:66:88
ipaddr=192.168.63.85
mmc_boot=setenv bootargs 'console=ttyS0,115200n8 root=/dev/mmcblk0p1 rw rootwait'; mmc dev 0; ext2load mmc 0 0x300000 /boot/uImage; bootm 0x300000
netmask=255.255.255.0
serverip=192.168.63.61
stderr=serial
stdin=serial
stdout=serial
watchdog=0

Environment size: 604/65532 bytes
U-Boot> 

U-Boot> bootp 0x200000
BOOTP broadcast 1
DHCP client bound to address 192.168.63.97
Using emac device
TFTP from server 192.168.63.61; our IP address is 192.168.63.97
Filename 'uImage'.
Load address: 0x200000
Loading: #################################################################
         ##########################
         2 MiB/s
done
Bytes transferred = 1321928 (142bc8 hex)

U-Boot> bootm 0x200000
## Booting kernel from Legacy Image at 00200000 ...
   Image Name:   Linux-3.18.122+
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    1321864 Bytes = 1.3 MiB
   Load Address: 00008000
   Entry Point:  00008000
   Verifying Checksum ... OK
SF: Detected MX25L12805D with page size 64 KiB, total 16 MiB
   Loading Kernel Image ... OK
OK
  
Starting kernel ...

Uncompressing Li done, booting t

**Comment by ponyatov** [comment]
Second test done with upgraded kernel-2.18.122 (under construction) from here: https://github.com/ponyatov/NUC970_Linux_Kernel/tree/3.18.122

First one with v1.5-nuc970.tar.gz

Test with most fresh snapshot of this repo will be next...

**Comment by ponyatov** [comment]
The same result for trunk 3.10 kernel:

U-Boot> bootm 0x200000
'## Booting kernel from Legacy Image at 00200000 ...'
   Image Name:   Linux kernel
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    1826864 Bytes = 1.7 MiB
   Load Address: 80008000
   Entry Point:  80008000
   Verifying Checksum ... OK
SF: Detected MX25L12805D with page size 64 KiB, total 16 MiB
   Loading Kernel Image ... OK
OK
  
Starting kernel ...

Uncompressing Li

**Comment by yachen** [comment]
Hi,

What part number are you using?


Sincerely,

Yi-An Chen

**Comment by ponyatov** [comment]
latest build  U-Boot 2013.04-rc2-geecdcf8  
built with with nuc970_config
h/w nuc906dk61y 
2750M008-ZZ2

constantly reboots in about 10-15 second while I'm staying in u-boot command line

NAND: no NAND device found

**Comment by ponyatov** [comment]
Problem isolated: kernel boot with D-Cache disabled

**Comment by ponyatov** [comment]
On nuc970dk62y original kernel build and runs ok
I'm going to check memory sizes for 61Y vs 62Y

**Comment by ponyatov** [comment]
I skipped tiny patch in arch/arm/kernel/atags_parse.c, all kernels boots ok
