### ISSUE TITLE
USB EHCI Debug Port support in kernel and hardware

### ISSUE THREAD

**Issue by ponyatov** [OpenNuvoton/NUC970_Linux_Kernel#28]
https://www.coreboot.org/EHCI_Debug_Port

https://mirrors.edge.kernel.org/pub/linux/kernel/people/jwessel/dbg_webinar/State_Of_kernel_debugging_LinuxCon2010.pdf

Are any attempts were done to enable EHCI-interfaced hardware debugging in nuc970 SoCs?

**Comment by ponyatov** [comment]
The advantage compared to classical JTAG is there is no requirement to have specially designed PCB with JTAG connector (I have no one module with JTAG on my desk now). You just plug USB cable to the device (yes, you lost and lock it only for debug session), and plug another end to a generic USB port on PC, no Jlink, no extra hw, works off the shelf (if enabled in).

**Comment by yachen** [comment]
Hi,

Our EHCI does not support EHCI appendix C. So it cannot support EHCI debug port.


Sincerely.

Yi-An Chen
