### ISSUE TITLE
Hardware debug via Ethernet/USB

### ISSUE THREAD

**Issue by ponyatov** [OpenNuvoton/NUC970_Linux_Kernel#30]
Need more info on hw-supported kernel-level debug for core drivers hacking.

I have a few devices w/o JTAG wiring, is it possible to transfer debug to generic interfaces?

**Comment by yachen** [comment]
No. It's impossible to send JTAG signal to other interface.
Maybe use kgdb through serial port to do kernel level debug?

**Comment by yachen** [comment]
Close because no further feedback for more than 3 months.
