### ISSUE TITLE
arch/arm/boot/dts/nuc970.dtsi pinmux issue for pinctrl_can0_PB

### ISSUE THREAD

**Issue by hotislandn** [OpenNuvoton/NUC970_Linux_Kernel#32]
It should be:
                                pinctrl_can0_PB: can0-PB {
                                        nuvoton,pins =
                                                <1 0xa 0xc 0
                                                 1 0xb 0xc 0>;
                                };

**Comment by yachen** [comment]
Fixed. Thanks.
