### ISSUE TITLE
About NUC970 chip ID

### ISSUE THREAD

**Issue by xuyi2008yi** [OpenNuvoton/NUC970_Linux_Kernel#38]
How can I get the unique ID of the nuc970?which register..

**Comment by yachen** [comment]
Hi, NUC970 does not have UID. It only as PDID and DID in SYS_PDID and SYS_PWRON registers.
Note: SYS_PDID is protected by Write-Protection Control Register, you'll have to unlock before read to get correct value.

**Comment by xuyi2008yi** [comment]
Thank you very much.It seems that I need to find another way to calculate the network MAC.

**Comment by xuyi2008yi** [comment]
Thank you very much.It seems that I need to find another way to calculate the network MAC.
