### ISSUE TITLE
Why hw kpi replaced to sw gpio kpi?

### ISSUE THREAD

**Issue by darkbrightness** [OpenNuvoton/NUC970_Linux_Kernel#39]
Hello! Could you please explain why did you replace hw kpi to gpio in keypad driver (https://github.com/OpenNuvoton/NUC970_Linux_Kernel/commit/0cf0ede7e90ca8448b4db3a934c7ef09d13ad97e)? Are there any problems with hw kpi?

**Comment by yachen** [comment]
Hi,

HW KPI cannot completely filter the noise on KPI interface, so replace with GPIO keypad.

Sincerely,

Yi-An Chen

**Comment by darkbrightness** [comment]
OK, thank you for answer!
