### ISSUE TITLE
How to build kernel with support for multiple LCD panels?

### ISSUE THREAD

**Issue by lightelf76** [OpenNuvoton/NUC970_Linux_Kernel#44]
Hi,
I need to build the kernel with support for different panels, like 320x240, 640x480, 800x480, so I can connect different panels to the boards with single kernel binaries. Panel selection can be with kernel command line or with some other way. Is it possible? What I need to do?

**Comment by yachen** [comment]
Hi, It's not possible with current driver. One possible solution is to use boot command to tell driver which panel it's connecting with.

**Comment by lightelf76** [comment]
Yup, thanks.
Did it this way
