### ISSUE TITLE
USB HUB Issue

### ISSUE THREAD

**Issue by jiuzhuaxiong** [OpenNuvoton/NUC970_Linux_Kernel#46]
When i connect the USB 2.0 GL528 USB HUB device to USB1 , it should be EHCI 2.0 ,and not OHCI 1.1, but it gives a wrong identify ? List the log below 
ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
ehci_nuc970_probe() - name: nuc970-ehci
nuc970-ehci nuc970-ehci: Nuvoton NUC970/N9H30 EHCI Host Controller
nuc970-ehci nuc970-ehci: new USB bus registered, assigned bus number 1
nuc970-ehci nuc970-ehci: irq 23, io mem 0xb0005000
nuc970-ehci nuc970-ehci: USB 2.0 started, EHCI 0.95
hub 1-0:1.0: USB hub found
hub 1-0:1.0: 2 ports detected
ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
nuc970-ohci nuc970-ohci: Nuvoton NUC970/N9H30 OHCI Host Controller
nuc970-ohci nuc970-ohci: new USB bus registered, assigned bus number 2
nuc970-ohci nuc970-ohci: irq 24, io mem 0xb0007000
hub 2-0:1.0: USB hub found
hub 2-0:1.0: 2 ports detected
usbcore: registered new interface driver usb-storage
usbcore: registered new interface driver usbserial
usbcore: registered new interface driver usbserial_generic
usbserial: USB Serial support registered for generic
usbcore: registered new interface driver option
usbserial: USB Serial support registered for GSM modem (1-port)
usbcore: registered new interface driver cdc_xr_usb_serial
xr_usb_serial_common: Exar USB UART (serial port) driver
nuc970-rtc nuc970-rtc: rtc core: registered nuc970-rtc as rtc0
i2c /dev entries driver
i2c i2c-1: Invalid 7-bit I2C address 0x00
i2c i2c-1: Can't create device at 0x00
nuc970-i2c1 nuc970-i2c1: i2c-1: nuc970 I2C adapter
--------------------------a----------------------------------------
softdog: Software Watchdog Timer: 0.08 initialized. soft_noboot=0 soft_margin=60 sec soft_panic=0 (nowayout=0)
ios->clock=400000
usbcore: registered new interface driver ushc
TCP: cubic registered
NET: Registered protocol family 10
sit: IPv6 over IPv4 tunneling driver
NET: Registered protocol family 17
nuc970-rtc nuc970-rtc: setting system clock to 2005-01-01 18:36:18 UTC (1104604578)
ios->clock=400000
ios->clock=400000
usb 2-2: new low-speed USB device number 2 using nuc970-ohci
usb 2-2: device descriptor read/64, error -62
usb 2-2: device descriptor read/64, error -62
ios->clock=400000
usb 2-2: new low-speed USB device number 3 using nuc970-ohci
ios->clock=300000
usb 2-2: device descriptor read/64, error -62
ios->clock=300000
ios->clock=300000
usb 2-2: device descriptor read/64, error -62
usb 2-2: new low-speed USB device number 4 using nuc970-ohci
usb 2-2: device not accepting address 4, error -62
usb 2-2: new low-speed USB device number 5 using nuc970-ohci
usb 2-2: device not accepting address 5, error -62
hub 2-0:1.0: unable to enumerate USB device on port 2

**Comment by yachen** [comment]
What board are you testing with, DEV board? This message seems to be signal quality issue.
