### ISSUE TITLE
Does spi support both spi flash and User mode SPI device driver ?

### ISSUE THREAD

**Issue by carpenter-larry** [OpenNuvoton/NUC970_Linux_Kernel#48]
My config is boot from spi flash, use jffs2 filesystem which is flashed on the spi flash, and  i select [User mode SPI device driver support] because i want to use a spi ADC chip. But when i boot from the spi flash, the kernel cannot find the root filesystem. When i unselect [User mode SPI device driver support], everything is OK.

**Comment by yachen** [comment]
Hi, Are you connecting ADC and SPI flash to the same SPI interface? If so, did you assign different chip_select for these two devices?
