### ISSUE TITLE
pnand_phyaddr type issue

### ISSUE THREAD

**Issue by xuganlai** [OpenNuvoton/NUC970_Linux_Kernel#50]
hi  
 now i have a issue:pnand_phyaddr the member of struct nuc970_nand_info type is  unsigned char * ,why not unsigned char?thanks.

**Comment by yachen** [comment]
Unsigned char can't hold address.

**Comment by xuganlai** [comment]
why before use it is not allocated.feel the usage have a risk.

**Comment by yachen** [comment]
It's allocated. Pls check probe function.
