### ISSUE TITLE
nuc970 spi does support slave mode?i know hardware is supported.

### ISSUE THREAD

**Issue by junwushi** [OpenNuvoton/NUC970_Linux_Kernel#52]
if not support, how can work with slave mode?

**Comment by yachen** [comment]
No, NUC970's SPI can not support slave mode. It's NUC980's SPI supports slave mode.

**Comment by junwushi** [comment]
if change to nuc 980, I want to use nuc980 memory virtual one SPI SRAM device , I do not know whether it is feasible
