### ISSUE TITLE
Does nuc970 watchdog has some trace information?

### ISSUE THREAD

**Issue by chenxy1988** [OpenNuvoton/NUC970_Linux_Kernel#60]
Hi Nuc team,

Recently, we found our product random reboot without any action, in order to spilt the root cause in application layer kernel layer or hardware layer(hope not :p), we have to add or enable debug trace when wdt is timeout, is there any way to do that?

Thanks!

Br,
Xiangyu

**Comment by yachen** [comment]
Not sure what do you mean by the "debug trace". You can dump the register SYS_RSTSTS for the cause of system reset source.

**Comment by chenxy1988** [comment]
Regarding SYS_RSTSTS, 
normally, system boot up, the value is 0x7, input "reboot" in linux, after boot complate, this value also 0x7. 
Kill the watchdog, system reset by wdt, after boot complate, this value is 0x27, input the "reboot" command, after boot complate, this value still 0x27 without change.
My question is does "reboot" command in linux no impact on SYS_RSTSTS register value?

Thanks.

**Comment by yachen** [comment]
Hi,

In order to get the latest reset source, please write 1s to clear this register after read.


Sincerely,

Yi-An Chen

**Comment by chenxy1988** [comment]
Many thanks! It's working correctly now ;)
