### ISSUE TITLE
Error while using make command

### ISSUE THREAD

**Issue by tkrelcon** [OpenNuvoton/NUC970_Linux_Kernel#61]
Dear Sir,

Can help out in below error as i am confused a little in this.

"**/usr/local/arm_linux_4.8/usr/bin/make: cannot execute binary file: Exec format error** "

**Comment by yachen** [comment]
That's an ARM executable. Are you executing it on a x86 machine?

**Comment by tkrelcon** [comment]
Please find below screen shots of Host window machine and Virtual Ubuntu. I am using Linux VDI downloaded from Nuvoton website only.
![VirtualBox_Ubuntu NUc_08_03_2021_14_56_37](https://user-images.githubusercontent.com/79750687/110301970-b39c8980-8033-11eb-8514-5f1745af6f47.png)
![Window host](https://user-images.githubusercontent.com/79750687/110301986-b7301080-8033-11eb-8a3d-6f266c5f5a07.jpg)

**Comment by yachen** [comment]
Please type "file /usr/local/arm_linux_4.8/usr/bin/make" to check the file format. It's a ARM executable (at least the file on my notebook is), so it cannot execute on X86 system.

**Comment by tkrelcon** [comment]
Yes sir, It is. 

user@ubuntu:~$ file /usr/local/arm_linux_4.8/usr/bin/make
/usr/local/arm_linux_4.8/usr/bin/make: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-, with debug_info, not stripped
user@ubuntu:~$

**Comment by tkrelcon** [comment]
How to remove this error?

**Comment by yachen** [comment]
You can't. This is a executable built for execute on an ARM CPU, but you're trying to execute it on a X86 machine.

**Comment by tkrelcon** [comment]
So for this i need 64 bit Linux OS ?

**Comment by yachen** [comment]
No. The "make" you're trying to execute is compile to ARM machine code.
X86 machine code is not execute ARM machine code. If you need a make for X86 Ubuntu, please use apt to download the correct version.

**Comment by tkrelcon** [comment]
Can you suggest further steps? Please. I am new for Ubuntu and Linux..
