### ISSUE TITLE
The serial port reception delay becomes larger.

### ISSUE THREAD

**Issue by qiubin2016** [OpenNuvoton/NUC970_Linux_Kernel#64]
commit id 87781d0654b85e58a478989712189f30cff30cef. 
After this commit id, the serial port receiving data delay becomes larger. The serial port reception delay is small before this commit id.

**Comment by yachen** [comment]
Hi, Back then we have a customer complained about the UART receive message is fragmented and their application has to resemble the data before processing them. So we modified the driver to buffer rx data and push to tty after RX FIFO empty or 1024B data is received. You can revert this commit in your local tree for better response time.
