### ISSUE TITLE
Newer kernel version?

### ISSUE THREAD

**Issue by ReimuNotMoe** [OpenNuvoton/NUC970_Linux_Kernel#73]
Hello.

I'm designing a new product and your NUC970 series is a perfect candidate (your NUC980 series lacks LCD controller). However this kernel version is way too old, it's **marked as end of life 4 years ago**, lacking new features I need, and **has multiple security issues**.

I know you don't have enough people to make your modifications mainlined (#36), but would you like to port them to a new longterm kernel version? Preferably 5.x versions.

Thank you very much.

**Comment by ychuang3** [comment]
HI,

We have no plan to port a new kernel version.

YC
