### ISSUE TITLE
how to add rotation function to framebuffer?

### ISSUE THREAD

**Issue by dong-higenis** [OpenNuvoton/NUC970_Linux_Kernel#74]
hello, 

we made a custom board with a nuc970 and i want to rotate the display 90 degrees while porting the LCD.

can I rotate the LCD 90 degrees?

how to add rotation function to framebuffer?

thank you

**Comment by ychuang3** [comment]
NUC970 LCD controller does not support image rotation.
Suggest to find a S/W rotation solution.

**Comment by dong-higenis** [comment]
ok thank you
