### ISSUE TITLE
编译出的镜像非常大是什么原因？

### ISSUE THREAD

**Issue by shishirong** [OpenNuvoton/NUC970_Linux_Kernel#81]
通过老项目的.config配置文件编译出的镜像只有2.74M，而使用nuc972_defconfig 编译出的镜像有47M，主要是什么原因造成的这么大的差距？
[old.config.zip](https://github.com/user-attachments/files/16279710/old.config.zip)

**Comment by ychuang3** [comment]
應該 rootfs 選擇了 ramfs, 這會把整個 rootfs 編進 kernel image

**Comment by shishirong** [comment]
是的，谢谢。
